#! /bin/sh

~/Tools/scripts/set-up-monitors.sh

sxhkd &

bspc monitor HDMI1 -d I II III IV
bspc monitor VGA1  -d V VI VII VIII

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Screenkey manage=off
