# Gruvbox Dark Theme

[colors]

# Default colors
primary.background = '0x282828' # hard contrast: background = '0x1d2021'
primary.foreground = '0xebdbb2' # soft contrast: background = '0x32302f'
  
# Normal colors
normal.black =   '0x282828'
normal.red =     '0xcc241d'
normal.green =   '0x98971a'
normal.yellow =  '0xd79921'
normal.blue =    '0x458588'
normal.magenta = '0xb16286'
normal.cyan =    '0x689d6a'
normal.white =   '0xa89984'

# Bright colors
bright.black =   '0x928374'
bright.red =     '0xfb4934'
bright.green =   '0xb8bb26'
bright.yellow =  '0xfabd2f'
bright.blue =    '0x83a598'
bright.magenta = '0xd3869b'
bright.cyan =    '0x8ec07c'
bright.white =   '0xebdbb2'
