[colors]

# Default colors
primary.background = '0x1f1f28' # hard contrast: background = '0x1d2021'
primary.foreground = '0xdcd7ba' # soft contrast: background = '0x32302f'
  
# Normal colors
normal.black =   '0x090618'
normal.red =     '0xc34043'
normal.green =   '0x76946a'
normal.yellow =  '0xc0a36e'
normal.blue =    '0x7e9cd8'
normal.magenta = '0x957fb8'
normal.cyan =    '0x6a9589'
normal.white =   '0xc8c093'

# Bright colors
bright.black =   '0x727169'
bright.red =     '0xe82424'
bright.green =   '0x98bb6c'
bright.yellow =  '0xe6c384'
bright.blue =    '0x7fb4ca'
bright.magenta = '0x938aa9'
bright.cyan =    '0x7aa89f'
bright.white =   '0xdcd7ba'

selection.background = '0x2d4f67'
selection.foreground = '0xc8c093'

# [[indexed_colors]]
# index = 16
# color = '0xffa066'

# [[indexed_colors]]
# index = 17
# color = '0xff5d62'
