general.import = ["~/.config/alacritty/themes/kanagawa_wave.toml"]

[window]
dimensions.columns = 108
dimensions.lines = 32
padding.x = 8 
padding.y = 2
decorations = "None"

[font]
normal.family = "UbuntuMono Nerd Font"
normal.style = "Regular"

[cursor]
style.blinking = "Always"
blink_interval = 500

[keyboard]
bindings = [
    { key = "N", mods = "Control | Shift", action = "SpawnNewInstance" },
    { key = "I", mods = "Command", chars = ". iara\r" },
    { key = "V", mods = "Command", chars = ". activate_venv\r" },
]
