[window]
# dimensions.columns = 108
# dimensions.lines = 32
padding.x = 8 
padding.y = 2
decorations = "None"

[font]
normal.family = "EffectsEighty"
# normal.family = "Terminus (TTF)"
# normal.family = "Monocraft"
normal.style = "Regular"
size = 18

[cursor]
style.shape = "Underline"
style.blinking = "Always"
blink_interval = 500
thickness = 0.25

[keyboard]
bindings = [
    { key = "N", mods = "Control | Shift", action = "SpawnNewInstance" },
    { key = "I", mods = "Command", chars = ". iara\r" },
    { key = "V", mods = "Command", chars = ". deactivate-venv\r" },
]
