general.import = ["~/.config/alacritty/themes/gruvbox_light.toml"]

[window]
# dimensions.columns = 108
# dimensions.lines = 32
padding.x = 8 
padding.y = 2
decorations = "None"

[font]
size = 16

[font.normal]
family = "EffectsEighty"
# family = "Monocraft Nerd Font"
style = "Regular"

[cursor]
blink_interval = 500
thickness = 0.2

[cursor.style]
blinking = "Always"
shape = "Underline"

[keyboard]
bindings = [
    { key = "N", mods = "Control | Shift", action = "SpawnNewInstance" },
    { key = "I", mods = "Command", chars = ". iara\r" },
    { key = "V", mods = "Command", chars = ". activate_venv\r" },
]
